import fs from 'fs';
import path from 'path';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { savePrivateFile } from '../utils/storage';

const PRIVATE_UPLOAD_DIR = process.env.PRIVATE_UPLOAD_DIR || './private_uploads';

function privatePath(relativePath: string) {
  return path.join(PRIVATE_UPLOAD_DIR, relativePath);
}

function parseSignatureData(signatureData: string) {
  const match = signatureData.match(/^data:image\/(png|jpeg|jpg);base64,(.+)$/i);
  if (!match) return null;
  return {
    type: match[1].toLowerCase() === 'png' ? 'png' : 'jpg',
    bytes: Buffer.from(match[2], 'base64'),
  };
}

export async function generateSignedLeasePdf(data: {
  originalFilePath?: string | null;
  leaseTitle: string;
  residentName: string;
  signatureData: string;
  signedAt: Date;
}) {
  let pdfDoc: PDFDocument;

  if (data.originalFilePath && fs.existsSync(privatePath(data.originalFilePath))) {
    try {
      const originalBytes = fs.readFileSync(privatePath(data.originalFilePath));
      pdfDoc = await PDFDocument.load(originalBytes);
    } catch {
      pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([612, 792]);
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      page.drawText(data.leaseTitle, { x: 54, y: 730, size: 18, font, color: rgb(0.05, 0.08, 0.13) });
      page.drawText('Original lease document could not be embedded.', { x: 54, y: 700, size: 11, font, color: rgb(0.35, 0.4, 0.5) });
    }
  } else {
    pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([612, 792]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    page.drawText(data.leaseTitle, { x: 54, y: 730, size: 18, font, color: rgb(0.05, 0.08, 0.13) });
    page.drawText('Original lease document was not attached.', { x: 54, y: 700, size: 11, font, color: rgb(0.35, 0.4, 0.5) });
  }

  const page = pdfDoc.addPage([612, 792]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const signedDate = new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeStyle: 'short' }).format(data.signedAt);

  page.drawText('Resident Electronic Signature', { x: 54, y: 720, size: 18, font: bold, color: rgb(0.05, 0.08, 0.13) });
  page.drawText(`Lease: ${data.leaseTitle}`, { x: 54, y: 688, size: 11, font });
  page.drawText(`Resident: ${data.residentName}`, { x: 54, y: 668, size: 11, font });
  page.drawText(`Signed: ${signedDate}`, { x: 54, y: 648, size: 11, font });

  const signature = parseSignatureData(data.signatureData);
  if (signature) {
    const image = signature.type === 'png' ? await pdfDoc.embedPng(signature.bytes) : await pdfDoc.embedJpg(signature.bytes);
    const width = 330;
    const height = Math.min(130, (image.height / image.width) * width);
    page.drawRectangle({ x: 54, y: 470, width: 360, height: 150, borderColor: rgb(0.8, 0.84, 0.9), borderWidth: 1 });
    page.drawImage(image, { x: 70, y: 490, width, height });
  } else {
    page.drawRectangle({ x: 54, y: 520, width: 360, height: 1, color: rgb(0.1, 0.12, 0.18) });
    page.drawText(data.signatureData || data.residentName, { x: 54, y: 540, size: 18, font });
  }

  page.drawText('This signed PDF is generated by HollerHub and should not be altered after completion.', {
    x: 54,
    y: 430,
    size: 10,
    font,
    color: rgb(0.4, 0.45, 0.55),
  });

  const bytes = await pdfDoc.save();
  return savePrivateFile(Buffer.from(bytes), `${data.leaseTitle.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-signed.pdf`, 'signed-leases');
}

export function resolvePrivateLeasePath(relativePath: string) {
  const fullPath = privatePath(relativePath);
  const resolvedRoot = path.resolve(PRIVATE_UPLOAD_DIR);
  const resolvedFile = path.resolve(fullPath);
  if (!resolvedFile.startsWith(resolvedRoot)) return null;
  if (!fs.existsSync(resolvedFile)) return null;
  return resolvedFile;
}
